name: Publish

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag to release"
        required: true
        default: ""
        type: string
  release:
    types: [published]

permissions:
  contents: write # for checkout

jobs:
  publish:
    uses: containifyci/.github/.github/workflows/artifacts.yml@v1
    secrets: inherit
    with:
      tag_name: ${{ github.event.release.tag_name || inputs.tag_name }}
